### ISSUE TITLE
Recommended Mondrian version

### ISSUE THREAD

**Issue by surendiranganesan** [mysticfall/pivot4j#181]
Hi, 

What is the recommended 

1) mondrian version

2)Java version

3)Tomcat version

Regards,

**Comment by mysticfall** [comment]
Hi,

The minimum requirement of Java verison which Pivot4J supports is ```1.7```. However, Pentaho is known to cause a problem if you're using Java 8 on Linux, so if you're running the plugin version on such an environment you'll probably need Java 7 and otherwise it's always recommended to use the latest version.

As to Mondrian, it is recommended to use the latest _3.6.x_ release, and currently it depends on the ```3.6.7``` version. It'll probably work with more recent versions but it's not yet tested.

And Pivot4J Analytics supports both Servlet 2.5 and 3.0 containers, so you can use the latest versions of Tomcat 6 and Tomcat 7 respectively.

It'll likely to be able to run without problem on Tomcat 8/Servlet 3.1 but I haven't yet tested this setup so I'm not too sure.

Hope this helps!

Regards,
Xavier
