### ISSUE TITLE
Same name dimension properties 

### ISSUE THREAD

**Issue by mkvoyager** [mysticfall/pivot4j#188]
Hi Xavier!
I'm doing some tests on properties and I found out this:
In the schema:

![schema](https://cloud.githubusercontent.com/assets/13120994/8693944/3b581d30-2adb-11e5-80d2-35f8950e3575.png)

MDX:

SELECT {[Measures].[Store Sqft], [Measures].[Grocery Sqft]} ON COLUMNS,
Hierarchize(Union(Union(Union(Union({[Store].[All Stores]}, [Store].[All Stores].Children),
[Store].[Canada].Children), [Store].[Canada].[BC].Children), [Store].[Canada].[BC].[Vancouver].Children))
ON ROWS FROM [Store]

RESULT:
![pivot](https://cloud.githubusercontent.com/assets/13120994/8693872/b24202e0-2ada-11e5-9c47-7058a61429a1.png)

But if properties have different name in the schema it's all ok. 
In JPivot if you have dimension properties with same names it shows you them in a one only column.
Another thing to say it's that I haven't java exception this time.

Can you try my mdx please?

**Comment by mysticfall** [comment]
It turns out ```Property.getUniqueName()``` does not return unique name for the property instance as it supposed to be, so I had to apply a workaround to avoid such a problem as above described.

It should be fixed in the latest build, so let me know if it does not works:
* http://ci.greencatsoft.com/job/Pivot4J/383/

Thanks for reporting this problem.

**Comment by mkvoyager** [comment]
Thanks a lot Xavier!
I'm going to do some tests in the weekend and i will let you know.
Bye!

**Comment by mkvoyager** [comment]
Hi!
I did some tests and measures columns are in the right position but I still have duplicated columns.
![immagine](https://cloud.githubusercontent.com/assets/13120994/8827439/ea559608-308c-11e5-84d2-af224799ab5f.png)

I updated all pivot4j-core src
Did I miss something?

**Comment by mysticfall** [comment]
It seems the problem is more complex than I initially thought. In this case (when the _'show parent'_ option is not selected), we cannot just merge those description columns, because they represent different properties even though they share the same name.

But I agree that the current way of rendering is plainly wrong, so I came up with a new rule to render member properties:

![issue-188](https://cloud.githubusercontent.com/assets/2367032/8892615/717f5c00-339d-11e5-8957-b0b542ea53e0.png)

I'm not sure if it's what you wanted, but I suppose it's at least more logically correct than the way it is.

Please let me know if you have questions or suggestions regarding this change.

**Comment by mkvoyager** [comment]
Hi Xavier,
thanks a lot for the fix! I agree that your last fix is more correct. 
do you mean that it's impossible to have the same jpivot behaviour or do you mean that it's really complex? I'm wondering why jpivot treats same name properties as same properties since you think it's not logically correct. 
I will do other tests and i will let you know the results.
Thanks again!

**Comment by mysticfall** [comment]
Hi, sorry for the late response again.

To return to the subject, it's little bit of both, actually.

First of all, I'm not sure if we can safely assume that properties with the same name defined in different levels are actually identical to each other. Maybe it's because I'm not very knowledgeable in Mondrian or OLAP, but I find it odd that we have to define each properties separately under respective levels in Mondrian schema, if in fact they are all identical.

And the relevant part in the codebase is notoriously difficult to change for now (that's why I made this issue: #88), so I'm a bit hesitant currently to modify it further without being certain that the current behavior is indeed wrong.

If you could give me more information about the correct behavior in handling properties with an identical name, I'll try to revisit this issue when I'll be able to work on this project again.

Thanks!
