### ISSUE TITLE
Column Selection in Drill Window does not work , related to issue 200

### ISSUE THREAD

**Issue by szymic1** [mysticfall/pivot4j#202]
I'm not sure how issue tracking functionality works on GitHub (I could not reopen #200 ) and I create also new issue: 

Hi, I've installed (using update n marketplace in Pentaho 6.1, is it right way to install?) and now it works a little better but bug still exists. To be honest there are 3 bugs.

First bug: https://youtu.be/O6MxiJ7CDHw
as you see it works with measures but when you want marked/unmarked rows related to dimension numbers of columns does not change :(

Second bug: https://youtu.be/wCORl2yp4LY
When you close Drill Window and you open once again this window and you check only one column two columns are displayed :(

Third bug: It is not severe bug but in my opinion should be fixed - when you open Drill Window parts of messaures/dimension are unmarked but columns are displayed.

**Comment by mysticfall** [comment]
I just committed the fix for the first two problems you mentioned, and it will be available shortly after I publish a new snapshot.

As to the last one, it's just way the API works when given an empty member selection. I can show a blank page initially, but I'm not too sure about it right now so I decided to leave it as it is until I'm convinced it is the right behavior (opinions are always welcomed :)).

Anyway, thanks again for the report.
